
name: build website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up Ruby and Install Gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
      working-directory: ./jekyll

    - name: Step 1 - Install Dependencies
      run: npm install
    - name: Step 2 - Build Project
      run: npm run build
    - name: Step 3 - copy contents into jekyll folder and cd
      run: cp -r dist/* jekyll && cd
    - name: Step 4 - run bundler install
      run: bundle install
    
